services:
  api-principal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qcyber_api_principal
    restart: always
    env_file:
      - .env
    environment:
       - MYSQL_HOST=mysql  # sobreescrita
       - MYSQL_PORT=3306  # sobreescrita
    networks:
      - qcyber-network  # mesma rede de containers do repositório QML


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: qcyber_nginx
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
      # - "443:443"  # não necessária se o Haproxy for "https terminator"
    depends_on:
      - api-principal
    restart: always
    networks:
      - qcyber-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # .conf da clausula http do nginx + clausula server da aplicação
      - ./nginx/frontend_build:/var/www:ro



networks:
  qcyber-network:
    driver: bridge
